uint32 id
geometry_msgs/Point     centroid
geometry_msgs/Point     centroid_vel
int16                   centroid_dir
geometry_msgs/Point[]   members
geometry_msgs/Point[]   members_vel
#Add more later by Poon
float64                 centroid_speed_mag      #magnitude of centroid's speed
float64                 centroid_speed_dir      #direction of centroid's speed
float64[]               members_speed_mag       #magnitude of each member's speed
float64[]               members_speed_dir       #direction of each member's speed

