#!/bin/bash

MAIN_FILES="administration.php customer.htm webviewer.htm"

PATTERN=""
for f in $MAIN_FILES; do
    PATTERN="$PATTERN -e $f"
done

SCRIPT_FILES=`ls *.php *.htm *.js | grep -v $PATTERN`

dest=/var/www/booking
rm -Rf $dest/*
cp $MAIN_FILES $dest
cp $SCRIPT_FILES $dest

rsync -avz --delete $dest/ -e ssh FMAutonomy:/usr/local/apache2/htdocs/booking
