#!/bin/bash

FILES="*.php webviewer.htm getxml.js"

echo "Uploading to FMAutonomy"
echo "-----------------------"
echo ""
rsync -avz -e ssh $FILES FMAutonomy:/var/www/dbserver/

echo ""
echo ""
echo "Uploading to localhost"
echo "----------------------"
echo ""
rsync -av $FILES /var/www/dbserver/