fixed_path: false
pruning_constant: 0
pathplan_ahead: 4.0

crash_penalty: -10000.0
reward_factor_vel: 0.5
reward_base_crash_vel: 0.4
belief_smoothing: 0.2
noise_robvel: 0.2
noise_goal_angle_deg: 45
max_vel: 2

ped_costmap:
    map_type: costmap
    global_frame: /map
    robot_base_frame: /base_link
    map_topic: map_cost
    static_map: true
    publish_frequency: 5
    robot_radius: 1.5
    inflation_radius: 5.0
    cost_scaling_factor: 5.0
    update_frequency: 2
    observation_sources: peds
    peds:
        topic: confident_objects_momdp
        clearing: true
        obstacle_range: 5000
        raytrace_range: 5000
    ped_cost_ratio: 0.6

planner:
    steering_limit_deg: 15
    yaw_res_deg: 1.0
    cost_steering_deg: 3
    steplen: 6
    num_search: 500000
    discretize_ratio: 0.3

