fixed_path: false
pruning_constant: 0
#pruning_constant: 1000000000
#pathplan_ahead: 3.0
pathplan_ahead: 1.5


crash_penalty: -1000.0
reward_factor_vel: 0.5
reward_base_crash_vel: 0.5
belief_smoothing: 0.05
noise_robvel: 0.1
noise_goal_angle_deg: 45
max_vel: 1.5
collision_distance: 1.5
infront_angle_deg: 70

ped_costmap:
    map_type: costmap
    global_frame: /map
    robot_base_frame: /base_link
    map_topic: map_cost
    static_map: true
    publish_frequency: 5
    robot_radius: 1.2
    inflation_radius: 7.0
    cost_scaling_factor: 4.0
    update_frequency: 2
    observation_sources: peds
    peds:
        #topic: confident_objects_momdp
        topic: ped_prediction
        clearing: true
        obstacle_range: 5000
        raytrace_range: 5000
    ped_cost_ratio: 0.9

planner:
    steering_limit_deg: 18
    yaw_res_deg: 1.0
    #cost_steering_deg: 30
    cost_steering_deg: 8
    steplen: 6
    num_search: 800000
    discretize_ratio: 0.3
    discount: 0.98

