"""autogenerated by genmsg_py from PedDataAssoc.msg. Do not edit."""
import roslib.message
import struct

import geometry_msgs.msg

class PedDataAssoc(roslib.message.Message):
  _md5sum = "675f42d80a78f56a6d510b19ea5677da"
  _type = "dataAssoc_experimental/PedDataAssoc"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 id        
geometry_msgs/Point32 ped_pose

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z
"""
  __slots__ = ['id','ped_pose']
  _slot_types = ['int32','geometry_msgs/Point32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       id,ped_pose
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(PedDataAssoc, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.ped_pose is None:
        self.ped_pose = geometry_msgs.msg.Point32()
    else:
      self.id = 0
      self.ped_pose = geometry_msgs.msg.Point32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_i3f.pack(_x.id, _x.ped_pose.x, _x.ped_pose.y, _x.ped_pose.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.ped_pose is None:
        self.ped_pose = geometry_msgs.msg.Point32()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.id, _x.ped_pose.x, _x.ped_pose.y, _x.ped_pose.z,) = _struct_i3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_i3f.pack(_x.id, _x.ped_pose.x, _x.ped_pose.y, _x.ped_pose.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.ped_pose is None:
        self.ped_pose = geometry_msgs.msg.Point32()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.id, _x.ped_pose.x, _x.ped_pose.y, _x.ped_pose.z,) = _struct_i3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_i3f = struct.Struct("<i3f")
