#!/bin/bash

# this script runs periodically. It checks whether ntp is still running (ntpd 
# sometimes hangs ...) and restarts if it is not running.

while [ 1 ]; do
    if [ "`service ntp status | grep not`" ]; then
        #ntp is not working
        service ntp start
	echo "start ntp service"
    else
	echo "process is running"	
    fi
    sleep 10
done
