#!/bin/bash

if [ -x parallel ]
then
    echo This requires GNU parallel to work >&2
    exit 1
fi

lvs="1 0.75 0.5 0.25 0.1 0.05 0.01"
lps="0.5 0.25 0.1 0.05 0.01"

# lvs="0.75 0.5 0.25 0.1 0.05 0.01"
# lps="0.25 0.1 0.05 0.01"

#opts="--sshlogin FMAutonomy,: --cleanup --return lv_{1}_lp_{2}.dat"

parallel --progress --eta $opts flow_sim_unit.py --lv={1} --lp={2} --logfile=lv_{1}_lp_{2}.dat ::: $lvs ::: $lps

tar cf result_logs.tar lv*dat