#!/bin/bash

# this script runs periodically. It checks whether ntp is still running (ntpd
# sometimes hangs ...) and restarts if it is not running. It also checks the
# offset and resynchronize with ntpdate if the offset is larger than a threshold

# The resync function: sync with ntpdate -b. NTP must be turned off...
resync() {
logger "ntpdwrapperd: resyncing"
service ntp stop
ntpdate -b golfcart-master
service ntp start
}

# The threshold: if the offset becomes larger than this value, then resync
offsetMax=50

logger "ntpdwrapperd: starting with a resync"
resync

while [ 1 ]
do
    sleep 10

    # awesome awk command found here:
    # http://www.zabbix.com/forum/showthread.php?t=7755
    # gives the offset to the golfcart-master
    offset=`ntpq -p | awk 'BEGIN { offset=1000 } $1 ~ /golfcart-master/ { offset=$9 } END { print offset }'`

    # absolute value: remove any minus sign:
    offset=${offset#-}

    # check whether ntp is still working
    if [ "`service ntp status | grep not`" ]
    then
        logger "ntpdwrapperd: ntpd is not working"
        resync

    # check the offset
    elif [[ $offset > $offsetMax ]]
    then
        logger "ntpdwrapperd: Offset is too high: $offset>$offsetMax"
        resync

    else
        logger "ntpdwrapperd: Offset is within limits: $offset<$offsetMax"

    fi

done
