#!/bin/bash

# this script runs periodically. It checks whether ntp is still running (ntpd 
# sometimes hangs ...) and restarts if it is not running.

while [ 1 ]; do
    if [ "`service ntp status | grep not`" ]; then
        #ntp is not working
        #run ntpdate to get rough sync and start ntp
        ntpdate golfcart-master
        service ntp start
    fi
    sleep 10
done
