#!/bin/bash

# the hostname can be provided as an argument. If not, use localhost
HOST=
if [ $# -gt 0 ]
then
    HOST="-h $1"
fi

# the directory where to find all the files is the one where the executable is located
d=`dirname $0`

if [ ! -r $d/createEmptyDatabase.sql ]
then
    echo "Could not find $d/createEmptyDatabase.sql, or it is not readable" > 2
    exit 1
fi

# Get the credentials from credentials.php
creds=$d/credentials.php
if [ ! -r $creds ]
then
    echo "Could not find credentials file $creds, or it is not readable" > 2
    exit 1
fi

# read the credentials from credentials.php
username=`grep username $creds | cut -d'"' -f2 | cut -d'"' -f1`
password=`grep password $creds | cut -d'"' -f2 | cut -d'"' -f1`
database=`grep database $creds | cut -d'"' -f2 | cut -d'"' -f1`

if [ -z $username -o -z $password -o -z $database ]
then
    echo "Could not read credentials from $creds" > 2
    exit 1
fi

mysql $HOST -u $username -p$password $database < $d/createEmptyDatabase.sql

exit
