#!/bin/bash
#This will copy .php files from current directory to /var/www/infrastructure/ folder and will appear on the web
echo "upload to... /var/www/infrastructure/"

rm /var/www/infrastructure/*
cp *.php /var/www/infrastructure/
